---
name: Pull Request Build, Tag, & Push
on:
  pull_request:
    branches:
      - develop
      - main
      - master
    types:
      - opened
      - reopened
      - synchronize
      - closed
# Defaults to building for linux/amd64. Can modify be updating variable, e.g. PLATFORMS: 'linux/amd64,linux/arm64/v8'
env:
  PLATFORMS: ${{ github.event.inputs.platforms }}
jobs:
  build-develop-open:
    if: github.base_ref == 'develop' && github.event.pull_request.merged == false
    uses: kbase/.github/.github/workflows/reusable_build.yml@multi-target
    with:
      platforms: ${{ env.PLATFORMS }}
    secrets: inherit
  build-develop-merge:
    if: github.base_ref == 'develop' && github.event.pull_request.merged == true
    uses: kbase/.github/.github/workflows/reusable_build-push.yml@multi-target
    with:
      name: '${{ github.event.repository.name }}-develop'
      tags: pr-${{ github.event.number }},latest
      platforms: ${{ env.PLATFORMS }}
    secrets: inherit
  build-main-open:
    if: (github.base_ref == 'main' || github.base_ref == 'master') && github.event.pull_request.merged == false
    uses: kbase/.github/.github/workflows/reusable_build-push.yml@multi-target
    with:
      name: '${{ github.event.repository.name }}'
      tags: pr-${{ github.event.number }}
      platforms: ${{ env.PLATFORMS }}
    secrets: inherit
  build-main-merge:
    if: (github.base_ref == 'main' || github.base_ref == 'master') && github.event.pull_request.merged == true
    uses: kbase/.github/.github/workflows/reusable_build-push.yml@multi-target
    with:
      name: '${{ github.event.repository.name }}'
      tags: pr-${{ github.event.number }},latest-rc
      platforms: ${{ env.PLATFORMS }}
    secrets: inherit
  trivy-scans:
    if: (github.base_ref == 'develop' || github.base_ref == 'main' || github.base_ref == 'master' ) && github.event.pull_request.merged == false
    uses: kbase/.github/.github/workflows/reusable_trivy-scans.yml@multi-target
    secrets: inherit
