---
name: Release - Build & Push Image
on:
  release:
    branches:
      - main
      - master
    types: [ published ]
# Defaults to building for linux/amd64. Can modify be updating variable, e.g. PLATFORMS: 'linux/amd64,linux/arm64/v8'
env:
  PLATFORMS: ${{ github.event.inputs.platforms }}
jobs:
  check-source-branch:
    uses: kbase/.github/.github/workflows/reusable_validate-branch.yml@multi-target
    with:
      build_branch: '${{ github.event.release.target_commitish }}'
  validate-release-tag:
    needs: check-source-branch
    uses: kbase/.github/.github/workflows/reusable_validate-release-tag.yml@multi-target
    with:
      release_tag: '${{ github.event.release.tag_name }}'
  build-push:
    needs: validate-release-tag
    uses: kbase/.github/.github/workflows/reusable_build-push.yml@multi-target
    with:
      name: '${{ github.event.repository.name }}'
      tags: '${{ github.event.release.tag_name }},latest'
      platforms: ${{ env.PLATFORMS }}
    secrets: inherit
